categories: [Metabolomics]
description: '[Metabolomics][W4M][LC-MS] XCMS R Package - Preprocessing - Refine choice of peaks'
homepage_url: http://workflow4metabolomics.org
long_description: 'Part of the W4M project: http://workflow4metabolomics.org XCMS:
  http://www.bioconductor.org/packages/release/bioc/html/xcms.html Remove or merge chromatographic peaks based on specific criteria.'
name: xcms_refine
owner: workflow4metabolomics
remote_repository_url: https://github.com/workflow4metabolomics/xcms
